version: "3.9"
services:
  nami:
    build: .
    image: nami
    volumes:
      - .:/nami
      - /nami/node_modules
  local-server:
    image: python:3.9.4-slim-buster
    volumes:
      - ./:/code
    ports:
      - 4000:8000
    working_dir: /code
    command: ["python", "-m", "http.server"]